name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [12.x, 14.x]
        prettier: [latest, 2.1, 2.2]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: npm i -g yarn
      - run: npx yarn install
      - run: npx yarn install prettier@${{ matrix.prettier }}
      - run: npm test
